services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
